export const INVITE_CODE_ERROR_CODES = {
  // 입력 검증 에러
  INVALID_INPUT: 'INVALID_INPUT',
  CODE_REQUIRED: 'CODE_REQUIRED',
  CODE_TOO_LONG: 'CODE_TOO_LONG',

  // 비즈니스 로직 에러
  INVALID_CODE: 'INVALID_CODE',
  INACTIVE_CODE: 'INACTIVE_CODE',
  EXPIRED_CODE: 'EXPIRED_CODE',
  MAX_USES_EXCEEDED: 'MAX_USES_EXCEEDED',

  // 서버 에러
  SERVER_ERROR: 'SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
} as const;

export type InviteCodeErrorCode =
  (typeof INVITE_CODE_ERROR_CODES)[keyof typeof INVITE_CODE_ERROR_CODES];
