export const INVITE_CODE_ERROR_CODES = {
  // 입력 검증 에러
  INVALID_INPUT: 'INVALID_INPUT',
  CODE_REQUIRED: 'CODE_REQUIRED',
  CODE_TOO_LONG: 'CODE_TOO_LONG',

  // 비즈니스 로직 에러
  INVALID_CODE: 'INVALID_CODE',
  INACTIVE_CODE: 'INACTIVE_CODE',
  EXPIRED_CODE: 'EXPIRED_CODE',
  MAX_USES_EXCEEDED: 'MAX_USES_EXCEEDED',

  // 서버 에러
  SERVER_ERROR: 'SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
} as const;

export type InviteCodeErrorCode =
  (typeof INVITE_CODE_ERROR_CODES)[keyof typeof INVITE_CODE_ERROR_CODES];

export const LINE_AUTH_ERROR_CODES = {
  // OAuth 에러
  LINE_OAUTH_ERROR: 'LINE_OAUTH_ERROR',
  MISSING_AUTH_CODE: 'MISSING_AUTH_CODE',
  INVALID_STATE: 'INVALID_STATE',
  STATE_EXPIRED: 'STATE_EXPIRED',

  // 토큰 교환 에러
  TOKEN_EXCHANGE_FAILED: 'TOKEN_EXCHANGE_FAILED',
  INVALID_REDIRECT_URI: 'INVALID_REDIRECT_URI',

  // 프로필 조회 에러
  PROFILE_FETCH_FAILED: 'PROFILE_FETCH_FAILED',
  INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',

  // Supabase 통합 에러
  USER_CREATION_FAILED: 'USER_CREATION_FAILED',
  SESSION_CREATION_FAILED: 'SESSION_CREATION_FAILED',
  LINE_LOGIN_FAILED: 'LINE_LOGIN_FAILED',

  // 일반 에러
  CALLBACK_FAILED: 'CALLBACK_FAILED',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type LineAuthErrorCode = (typeof LINE_AUTH_ERROR_CODES)[keyof typeof LINE_AUTH_ERROR_CODES];
